# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true
### Tabler Icon: https://tabler.io/icons

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/penguin04172"
weight = 1

[social.params]
icon = "brand-github"

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://facebook.com/penguin04172"
weight = 2

[social.params]
icon = "brand-facebook"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://instagram.com/penguin04172"
weight = 3

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "Mail"
name = "Mail"
url = "mailto:sylin4172@gmail.com"
weight = 4

[social.params]
icon = "brand-gmail"
